apiVersion: v1
kind: Pod
metadata:
  name:  test-backend
  labels:
    name:  test-backend-pod
    app: test-app
spec:
  containers:
    - name:  backend-contanier
      image:  sabarivig/test-server:0.0.2
      ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: test-network
  labels:
    name: backend-service
    app: test-app
spec:
  type: LoadBalancer
  ports:
  - name:  backend-port
    port:  8080
    targetPort: 8080
  selector:
    name:  test-backend-pod
    app: test-app
