apiVersion: apps/v1
kind: Deploymen
metadata:
  name: backend
  labels:
    name: backend-app
    app: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name:  test-backend-pod
      app: test-app
  template:
    metadata:
      name:  test-backend
      labels:
        name:  test-backend-pod
        app: test-app
    spec:
      containers:
        - name:  backend-contanier
          image:  sabarivig/test-server:0.0.2
          ports:
            - containerPort: 8080




---
apiVersion: v1
kind: Service
metadata:
  name: test-network
  labels:
    name: backend-service
    app: test-app
spec:
  type: LoadBalancer
  ports:
  - name:  backend-port
    port:  8080
    targetPort: 8080
  selector:
    name: test-backend-pod
    app: test-app

