apiVersion: apps/v1
kind: Deploymen
metadata:
  name: backend
  labels:
    name: backend-app
    app: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name:  test-backend-pod
      app: test-app
  template:
    metadata:
      name:  test-backend
      labels:
        name:  test-backend-pod
        app: test-app
    spec:
      containers:
        - name:  backend-contanier
          image:  sabarivig/test-server:0.0.3
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: backend-config




---
apiVersion: v1
kind: Service
metadata:
  name: server
  labels:
    name: backend-service
    app: test-app
spec:
  type: LoadBalancer
  ports:
  - name:  backend-port
    port:  8080
    targetPort: 8080
  selector:
    name: test-backend-pod
    app: test-app

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  MONGO:"mongodb://localhost:27017/test"
  REDIS_URL:redis
  REDIS_PORT:6379
  API_KEY:lD1kuNzap9chSyPn11IeL7YfBF3hjOl4OrYRSnxyq09WMVFfIR6vIwf27k0Y