apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    name: frontend-deployment
    app: test-app
spec:
  replicas: 3
  selector:
    matchLabels:
      name: test-frontend-pod
      app: test-app
  template:
    metadata:
      name: web
      labels:
        name: test-frontend-pod
        app: test-app
    spec:
      containers:
        - name: frontend-contanier
          image: sabarivig/test-web:0.0.3         
          ports:
          - containerPort:  80


---

apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web-service
    app : test-app
spec:
  type: LoadBalancer
  ports:
  - name: web-port
    port: 80
    targetPort: 80
  selector: 
    name:  test-frontend-pod
    app: test-app




