apiVersion: v1
kind: Pod
metadata:
  name:  redis
  labels:
    name:  redis-pod
    app: test-app
spec:
  containers:
    - name:  redis-contanier
      image:  redis
      ports:
        - containerPort: 6379

---

kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: test-app
spec:
  ports:
  - name:  redis-port
    port:  6379
    targetPort: 6379
  selector:
    name:  redis-pod
    app: test-app

