apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  labels:
    name:  redis-deployment
    app: test-app
spec:
  replicas: 1
  selector:
    matchLables:
      name:  redis-pod
      app: test-app
  template:
    metadata:
      name: redis
      labels:
        name: redis-pod
        app: test-app
    spec:
      containers:
      - name: redis-contanier
        image: redis
        ports:
        -  containerPort:  6379

---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    name: redis-service
    app: test-app
spec:
  ports:
  - name:  redis-port
    port:  6379
    targetPort: 6379
  selector:
    name:  redis-pod
    app: test-app
